mysite/main/urls.py
from django.urls import path
from . import views
from main.views import *
from django.conf import settings
from django.conf.urls.static import static


app_name = 'main'  # here for namespacing of urls.

urlpatterns = [
    path('', AplikacijaList.as_view()),
    path('<aplikacija_naziv>', AplikacijaPregledList.as_view())
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include #importamo include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('main.urls')), #dodajemo urls
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/main/models.py
from django.db import models

# Create your models here.

class Student(models.Model):
    student_ime=models.CharField(max_length=50)
    student_prezime=models.CharField(max_length=50)
    student_email=models.EmailField()

    def __str__(self):
        return '{} {}'.format(self.student_ime, self.student_prezime)

class Aplikacija(models.Model):
    aplikacija_naziv=models.CharField(max_length=100)
    aplikacija_opis=models.TextField()
    aplikacija_datum=models.DateField()
    aplikacija_URL=models.URLField(null=True,blank=True,)
    aplikacija_AkGod=models.CharField(max_length=30)
    aplikacija_slika=models.ImageField(null=True, blank=True, upload_to='media')
    aplikacija_slika1=models.ImageField(null=True, blank=True, upload_to='media')
    aplikacija_slika2=models.ImageField(null=True, blank=True, upload_to='media')
    aplikacija_slika3=models.ImageField(null=True, blank=True, upload_to='media')
    aplikacija_slika4=models.ImageField(null=True, blank=True, upload_to='media')
    aplikacija_student=models.ManyToManyField(Student)

    def __str__(self):
        return self.aplikacija_naziv

mysite/main/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.http import HttpResponse
from main.models import Aplikacija


## Create your views here.
class AplikacijaList(ListView):
    model=Aplikacija
    def get_queryset(self):
        selected_value = self.request.GET.get('aplikacija_AkGod')
        if selected_value:
            queryset = Aplikacija.objects.filter(aplikacija_AkGod=selected_value)
        else:
            queryset = Aplikacija.objects.all()
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        selected_value = self.request.GET.get('aplikacija_AkGod')
        context['selected_value'] = selected_value
        context['ak_god'] = Aplikacija.objects.order_by("aplikacija_AkGod").values_list('aplikacija_AkGod', flat=True).distinct()
        return context

class AplikacijaPregledList(ListView):
    template_name='main/aplikacijaPregled_list.html'
    def get_queryset(self):
        self.aplikacija_naziv=get_object_or_404(Aplikacija, aplikacija_naziv=self.kwargs['aplikacija_naziv'])
        return Aplikacija.objects.filter(aplikacija_naziv=self.aplikacija_naziv)

mysite/main/templates/main/aplikacijaPregled_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Stranica Aplikacije</title>
</head>
<ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/"><strong>Povratak na popis aplikacija</strong></a></li>
</ol>
<body style="margin-top:20px; margin-left: 250px; margin-right: 250px;">
    
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <link rel="" type="text/css" href="{% static 'bootstrap.min.css' %}"> 
    
    {% block content %}
    <br>
 
        {% for aplikacija in aplikacija_list %}
        <div class="row">
        <div class="col">
        <h3 style="margin-top: 15px;"><strong>{{aplikacija.aplikacija_naziv}}</strong></h3>
        <h6 class="text-muted">Autori: {% for student in aplikacija.aplikacija_student.all %}{{student}}{% if not forloop.last %}, {% endif %}{% endfor %} </h6></div>
        {% if aplikacija.aplikacija_URL %}
        <div class="col"><a href="{{aplikacija.aplikacija_URL}}"><button type="button" style="position: inherit; background-color: rgba(207, 56, 1, 0.918); width: 170px; height: 60px; font-size: large; float: right; margin: 10px;" class="btn" ><strong>Posjeti</strong></button></a></div>
        {% endif %}    
        </div>
        <div class="row">
        <div class="col">{% load static %}<img src="{{aplikacija.aplikacija_slika}}" alt="NaslovnaSLika" class="responsive" style="border-radius: 1%; width: 100%; height: 500px; margin-left: auto; margin-right: auto;"></div>
        </div><br>
        <div class="row">
        <div class="col" style="text-align: left;"><h4><strong>Akademska godina: </strong>{{aplikacija.aplikacija_AkGod}}</h4></div>
         <!--<div class="col"><h4><strong>Objavljeno:</strong> {{aplikacija.aplikacija_datum}}</h4></div>-->
        </div><br>
         <h4><strong>Opis</strong></h4><hr>
         <h6>{{aplikacija.aplikacija_opis}}</h6><hr>
        <h4><strong>Slike aplikacije:</strong></h4>
        <div class="col" >
        {% load static %}
        {% if aplikacija.aplikacija_slika1 %}
        <img src="{{aplikacija.aplikacija_slika1}}" alt="SlikaUListi" class="responsive" style="border-radius: 1%; width: 49%; height: 500px; margin-left: auto; margin-right: 14px; margin-top:15px;">
        {% endif %}
        {% if aplikacija.aplikacija_slika2 %}
        <img src="{{aplikacija.aplikacija_slika2}}" alt="SlikaUListi" class="responsive" style="border-radius: 1%; width: 49%; height: 500px; margin-left: auto; margin-right: auto; margin-top:15px;">
        {% endif %}
        {% if aplikacija.aplikacija_slika3 %}
        <img src="{{aplikacija.aplikacija_slika3}}" alt="SlikaUListi" class="responsive" style="border-radius: 1%; width: 49%; height: 500px; margin-left: auto; margin-right: 14px; margin-top:15px;">
        {% endif %}
        {% if aplikacija.aplikacija_slika4 %}
        <img src="{{aplikacija.aplikacija_slika4}}" alt="SlikaUListi" class="responsive" style="border-radius: 1%; width: 49%; height: 500px; margin-left: auto; margin-right: auto; margin-top:15px;">  
        {% endif %}
    </div>
        <hr>
        {% endfor %}

   
    {% endblock %}

</body>
</html>

mysite/main/templates/main/aplikacija_list.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>UpraviteljAplikacija</title>
</head>

<body>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">


    {% block content %}
    <br>
    <h2 style="margin-top: 15px; margin-left: 20px;"><strong>Upravitelj Aplikacija studenata</strong></h2><br>
    <p style="margin-left: 20px;">Ova usluga omogućuje upravljanje i pregled različitih aplikacija studenata. U nastavku
        se nalazi popis svih
        aplikacija koje je moguće filtrirati po akademskoj godini.<br>
        Odabirom željene aplikacije pojavljuju se detaljnije informacije o njenoj namjeni te je omogućen i odlazak na
        samu
        aplikaciju putem poveznice.</p><br>

    <h3 style="margin: 20px"><strong>Aplikacije:</strong></h3><hr>
    
    <form method="get">
        <label for="filter-akgod" style="margin-left:50px">Filter po akademskog godini:</label>
        <select id="filter-akgod" name="aplikacija_AkGod">
            <option value=""{% if selected_value == "" %} selected{% endif %}>Odaberi Ak.God</option>
            <{% for god in ak_god %}
            <option value="{{ god }}">{{ god }}</option>
            {% endfor %}
        </select>
        <button type="submit">Filter</button>
    </form>
    
    <br>
    <div class="row mx-auto" style="margin-top: 20px">
        
        {% for aplikacija in aplikacija_list %}
        <div class="card col-12 col-md-6 col-lg-4 mb-5 mx-auto" style="width: 560px; border-color: rgb(83, 83, 83); border-width: 5px; border-radius: 2%;">
            
            <div class="card-body mx-1">
                <a href="{{aplikacija.aplikacija_naziv}}"><img src="{{aplikacija.aplikacija_slika}}" class="card-img-top" alt="Thumbnail" width="auto" height="300" style="border-radius: 2%"/></a><br>
                <br>
                <h5 class="card-title"><strong><a href="{{aplikacija.aplikacija_naziv}}">{{aplikacija.aplikacija_naziv}}</a></strong></h5>
                <h6 class="card-title">Autori: {% for student in aplikacija.aplikacija_student.all %}{{student}}{% if not forloop.last %}, {% endif %}{% endfor %}</h6><br>
                <div class="row">
                <!--<div class="col"><h6 class="card-subtitle text-muted">Datum: {{aplikacija.aplikacija_datum}}</h6></div>-->
                <div class="col"><h6 class="card-subtitle text-muted" style="float: left;">Ak. godina: {{aplikacija.aplikacija_AkGod}}</h6></div>
                 </div>
            </div> 
        </div>
    
        {% endfor %}
    </div>
   
    {% endblock %}

</body>

</html>